### PR TITLE
Alvar/edit entry

### PR DESCRIPTION
**Pull request by alvarix**
Chad, making this pull request bcs Im finding an error with dropbox save. 
It's hard to reproduce but I think it happens when I trigger edit more than once (see attached).
I also produced it on main by clicking copy more than once.

edit
main branch  (add)

### CODE REVIEW

**Comment by alvarix** [comment]
@chadcrume I think this PR is ready for review and merge

**Comment by alvarix** [comment]
@chadcrume woops I forgot to make a new branch for display DBX account, so it's in this PR

**Comment by alvarix** [comment]
@chadcrume 
Trying to find my place in editEntry. 

I believe we agreed that instead of implementing an edit/save button, it's better to go with focus and blur to trigger editing. 

I wonder if that will lead to unintentional or editing.
On desktop do people click on what they're reading out of habit?
On mobile surely edit will be triggered just by scrolling.

I may go ahead and try it so we can test for ourselves, but curious what you think

**Comment by chadcrume** [comment]
@alvarix , what's the status of this PR?

**Comment by chadcrume** [comment]
@alvarix , nevermind. It mered with #113

**Pull request merged**
